version: "2.1"

services:
  leader:
    build: ./9.6
    container_name: pgleader
    healthcheck:
      test: ["CMD", "psql -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  replica:
    build: ./11
    container_name: pgreplica
    depends_on:
      leader:
        condition: service_healthy

 
